# Generated by Django 5.0.2 on 2024-03-06 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_passby_alter_student_roll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='city',
        ),
        migrations.RemoveField(
            model_name='student',
            name='passby',
        ),
    ]
